name: "Update Localisation"
on:
  workflow_dispatch

jobs:
  updateLoc:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Process localisation files
        uses: TTFTCUTS/Stellaris-Loc-Action@main
        with:
          path: localisation
          source-language: english
          output-languages: braz_por, french, german, polish, russian, simp_chinese, spanish
      - name: Process localisation replacement files
        uses: TTFTCUTS/Stellaris-Loc-Action@main
        with:
          path: localisation/replace
          source-language: english
          output-languages: braz_por, french, german, polish, russian, simp_chinese, spanish
      - name: Commit any changes
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: Update loc files
          add: localisation
          committer_name: GitHub actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
      
